### ISSUE TITLE
Number of done tasks in student profile is higher than in ranking

### ISSUE THREAD

**Issue by poxip** [svineet/GCILeaderboard#3]
Looks like 2 iterations or sth. In exmaple: ![](http://i.imgur.com/GPyPJIZ.png)
but I've done only 3 tasks.

**Comment by i5o** [comment]
Can you try again? I cant reproduce
![captura de pantalla de 2014-12-02 18 26 51](https://cloud.githubusercontent.com/assets/2650479/5270780/62c751ec-7a55-11e4-81a2-ffca55392996.png)

**Comment by poxip** [comment]
@ignaciouy Now works well. Strange.

**Comment by samdroid-apps** [comment]
Issue fixed?  Can we close @ignaciouy

**Comment by i5o** [comment]
Oh, sorry. Yes, fixed

Ignacio Rodríguez
nachoel01@gmail.com
SugarLabs at Facebook
https://www.facebook.com/pages/SugarLabs/187845102582

2014-12-04 4:32 GMT-02:00 Sam notifications@github.com:
